### ISSUE TITLE
Some so-called countries aren't actually countries

### ISSUE THREAD

**Issue by Theotime812** [bolorundurovj/Covid19-Tracker-v2#8]
**Is your feature request related to a problem? Please describe.**
Some countries have several pins, representing cities (e.g. in Sweden), or states (e.g. in the USA) for example. However, the stats present every pin as a country (for example: "Country: Uppsala", although Uppsala is a Swedish city.).

**Describe the solution you'd like**
Stats should start with "City: ..." or "State: ..." for example, when relevant.

**Describe alternatives you've considered**
Having only one pin per country.

**Additional context**
![Capture d’écran du 2020-10-17 15-13-31](https://user-images.githubusercontent.com/45947878/96338310-58bac380-108d-11eb-98a2-c1dd21b6ba56.png)

**Comment by bolorundurovj** [comment]
Thanks for bringing this to my attention. I'll work on this.

**Comment by dzienisz** [comment]
Maybe you should change the icon? I wouldn't change to country because in this view you have very specific data to every region.

**Comment by bolorundurovj** [comment]
> Maybe you should change the icon? I wouldn't change to country because in this view you have very specific data to every region.
Thanks... that is quite good. I think i will just display as is for country data, and for specific data, i will indicate the country and city name as it should be more practical.
